# パラメータ
LOT : 0.001
EXCHANGE : bitflyer
SYMBOL : BTC/JPY
API_KEY : 2vxQkYKLGv5tyZ1cj2ZZR6
API_SECRET : yHiuA6bgcEKv//5U2wJo+D+Tm54QgnDVtJ6x4VtTpQM=
LONG_THRESHOLD: -0.048
SHORT_THRESHOLD: 0.048
MAX_POSITION_SIZE: 0.005